// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCXwW7QChMTIrX6h2f8-eVV-vpnhrFIMQ',
    appId: '1:429883198452:web:f0be522ee7f7b95813c7a1',
    messagingSenderId: '429883198452',
    projectId: 'petpalhealth',
    authDomain: 'petpalhealth.firebaseapp.com',
    storageBucket: 'petpalhealth.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOgUGhqxsvgH5FahG2buiIHCwClrwiY_U',
    appId: '1:429883198452:android:c4976dbdf54ddace13c7a1',
    messagingSenderId: '429883198452',
    projectId: 'petpalhealth',
    storageBucket: 'petpalhealth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa99go7ZGh7JWj0bGgloeFkP_lcwgO794',
    appId: '1:429883198452:ios:607b9c8a45d00de113c7a1',
    messagingSenderId: '429883198452',
    projectId: 'petpalhealth',
    storageBucket: 'petpalhealth.appspot.com',
    iosBundleId: 'com.example.petpal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDa99go7ZGh7JWj0bGgloeFkP_lcwgO794',
    appId: '1:429883198452:ios:4d6a46b1371628e513c7a1',
    messagingSenderId: '429883198452',
    projectId: 'petpalhealth',
    storageBucket: 'petpalhealth.appspot.com',
    iosBundleId: 'com.example.petpal.RunnerTests',
  );
}
